apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: devops-project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        role: application
        
      containers:
      - name: backend
        image: theena18/notes-backend:f942e675c5a35ece209dbeaf10e14b7020f21f1b
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"

          limits:
            cpu: "200m"
            memory: "256Mi"

        ports:
        - containerPort: 5000

        env:
        - name: MONGO_URL
          value: "mongodb://mongodb-service:27017/notesdb"

        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3 