version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/db

  backend:
    image: theena18/notes-backend
    environment:
      - MONGO_URL=mongodb://mongodb:27017/notesdb

  frontend:
    image: theena18/notes-frontend
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

    
volumes:
  mongo-data: