apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: devops-project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend
    
    spec:
      nodeSelector:
        role: application
        
      containers:
      - name: frontend
        image: theena18/notes-frontend:7a558cbf15c9a2274ec55da2a5e19347308817f2
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        ports:
        - containerPort: 80