apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: devops-project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend
  
  template:
    metadata:
      labels:
        app: frontend
    
    spec:
      nodeSelector:
        role: application
        
      containers:
      - name: frontend
        image: theena18/notes-frontend:7798345a58ed8d91159352e3172965eefedfcea1
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "5m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        ports:
        - containerPort: 80