
- name: Configure server
  hosts: web
  become: yes

  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create nginx folder
      file:
        path: /home/ubuntu/nginx
        state: directory

    - name: Copy nginx config
      copy:
        src: ../fullstackapp/nginx/nginx.conf
        dest: /home/ubuntu/nginx/nginx.conf

    - name: Copy Docker Compose file
      copy:
        src: ../fullstackapp/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Stop old containers
      command: docker-compose down
      args:
        chdir: /home/ubuntu

    - name: Run application using docker-compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
    
    - name: Dedbug monitoring files
      command: ls -l {{playbook_dir }}/../fullstackapp/monitoring/
    
    - name: Create monitoring folder
      file:
        path: /home/ubuntu/monitoring
        state: directory

    - name: Copy monitoring config file
      copy:
        src: "{{ playbook_dir }}/../fullstackapp/monitoring/prometheus.yml"
        dest: /home/ubuntu/monitoring/prometheus.yml